version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "A:automerge"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "A:automerge"
      - dependencies

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    target-branch: "release/0.5.x"
    open-pull-requests-limit: 0
    labels:
      - dependencies

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    target-branch: "main"
    open-pull-requests-limit: 0
    labels:
      - dependencies
