// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: saga/admin/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	types "github.com/cosmos/cosmos-sdk/x/bank/types"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgEnable struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgEnable) Reset()         { *m = MsgEnable{} }
func (m *MsgEnable) String() string { return proto.CompactTextString(m) }
func (*MsgEnable) ProtoMessage()    {}
func (*MsgEnable) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be15843df3dbf51, []int{0}
}
func (m *MsgEnable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnable.Merge(m, src)
}
func (m *MsgEnable) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnable) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnable.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnable proto.InternalMessageInfo

func (m *MsgEnable) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgEnableResponse struct {
}

func (m *MsgEnableResponse) Reset()         { *m = MsgEnableResponse{} }
func (m *MsgEnableResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEnableResponse) ProtoMessage()    {}
func (*MsgEnableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be15843df3dbf51, []int{1}
}
func (m *MsgEnableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnableResponse.Merge(m, src)
}
func (m *MsgEnableResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnableResponse proto.InternalMessageInfo

type MsgDisable struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgDisable) Reset()         { *m = MsgDisable{} }
func (m *MsgDisable) String() string { return proto.CompactTextString(m) }
func (*MsgDisable) ProtoMessage()    {}
func (*MsgDisable) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be15843df3dbf51, []int{2}
}
func (m *MsgDisable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisable.Merge(m, src)
}
func (m *MsgDisable) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisable) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisable.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisable proto.InternalMessageInfo

func (m *MsgDisable) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgDisableResponse struct {
}

func (m *MsgDisableResponse) Reset()         { *m = MsgDisableResponse{} }
func (m *MsgDisableResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDisableResponse) ProtoMessage()    {}
func (*MsgDisableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be15843df3dbf51, []int{3}
}
func (m *MsgDisableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableResponse.Merge(m, src)
}
func (m *MsgDisableResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableResponse proto.InternalMessageInfo

// MsgSetMetadata is the Msg/MsgSetMetadata request type.
type MsgSetMetadata struct {
	Authority string          `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Metadata  *types.Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *MsgSetMetadata) Reset()         { *m = MsgSetMetadata{} }
func (m *MsgSetMetadata) String() string { return proto.CompactTextString(m) }
func (*MsgSetMetadata) ProtoMessage()    {}
func (*MsgSetMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be15843df3dbf51, []int{4}
}
func (m *MsgSetMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetMetadata.Merge(m, src)
}
func (m *MsgSetMetadata) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetMetadata proto.InternalMessageInfo

func (m *MsgSetMetadata) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetMetadata) GetMetadata() *types.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type MsgSetMetadataResponse struct {
}

func (m *MsgSetMetadataResponse) Reset()         { *m = MsgSetMetadataResponse{} }
func (m *MsgSetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetMetadataResponse) ProtoMessage()    {}
func (*MsgSetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be15843df3dbf51, []int{5}
}
func (m *MsgSetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetMetadataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetMetadataResponse.Merge(m, src)
}
func (m *MsgSetMetadataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetMetadataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgEnable)(nil), "saga.admin.v1.MsgEnable")
	proto.RegisterType((*MsgEnableResponse)(nil), "saga.admin.v1.MsgEnableResponse")
	proto.RegisterType((*MsgDisable)(nil), "saga.admin.v1.MsgDisable")
	proto.RegisterType((*MsgDisableResponse)(nil), "saga.admin.v1.MsgDisableResponse")
	proto.RegisterType((*MsgSetMetadata)(nil), "saga.admin.v1.MsgSetMetadata")
	proto.RegisterType((*MsgSetMetadataResponse)(nil), "saga.admin.v1.MsgSetMetadataResponse")
}

func init() { proto.RegisterFile("saga/admin/v1/tx.proto", fileDescriptor_1be15843df3dbf51) }

var fileDescriptor_1be15843df3dbf51 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0x21, 0x06, 0x35, 0x62, 0x12, 0x61, 0x1a, 0x69, 0x80, 0x28, 0xeb, 0x69, 0x4c,
	0x9a, 0xad, 0x0c, 0x09, 0x09, 0x6e, 0x0c, 0x38, 0xe6, 0xd2, 0x72, 0xe2, 0x82, 0x9c, 0xc5, 0x78,
	0x61, 0x8d, 0x1d, 0xe5, 0xb9, 0x55, 0xcb, 0x09, 0xf5, 0x13, 0x20, 0xf5, 0x8b, 0xf4, 0xc0, 0x87,
	0xe0, 0x58, 0xc1, 0x85, 0x63, 0xd5, 0x22, 0xf5, 0x6b, 0xa0, 0x3a, 0x6e, 0xaa, 0x52, 0xf5, 0x82,
	0x76, 0x8a, 0xfe, 0xfe, 0xbf, 0xfc, 0xfe, 0xcf, 0xcf, 0x0f, 0x1f, 0x01, 0x13, 0x8c, 0xb2, 0x24,
	0x4b, 0x25, 0xed, 0x85, 0x54, 0xf7, 0x49, 0x5e, 0x28, 0xad, 0x9c, 0xfb, 0xcb, 0x73, 0x62, 0xce,
	0x49, 0x2f, 0xf4, 0x9e, 0x08, 0xa5, 0x44, 0x87, 0x53, 0x96, 0xa7, 0x94, 0x49, 0xa9, 0x34, 0xd3,
	0xa9, 0x92, 0x50, 0x16, 0x7b, 0x8d, 0x4b, 0x05, 0x99, 0x82, 0x8f, 0x46, 0xd1, 0x52, 0x58, 0xeb,
	0x51, 0xa9, 0x68, 0x06, 0x62, 0xc9, 0xcf, 0x40, 0x58, 0xc3, 0xb7, 0x46, 0xcc, 0xe4, 0x35, 0xed,
	0x85, 0x31, 0xd7, 0x2c, 0x34, 0xa2, 0xf4, 0x9b, 0x6d, 0x5c, 0x8f, 0x40, 0xbc, 0x93, 0x2c, 0xee,
	0x70, 0xe7, 0x05, 0xae, 0xb3, 0xae, 0xbe, 0x52, 0x45, 0xaa, 0x07, 0x2e, 0x0a, 0xd0, 0x49, 0xfd,
	0xc2, 0xfd, 0xf9, 0xfd, 0xec, 0xd0, 0x46, 0xbd, 0x4e, 0x92, 0x82, 0x03, 0xb4, 0x75, 0x91, 0x4a,
	0xd1, 0x5a, 0x97, 0xbe, 0x3a, 0x18, 0x2e, 0xc6, 0xa7, 0x6b, 0xdd, 0x7c, 0x88, 0x1f, 0x54, 0xd0,
	0x16, 0x87, 0x5c, 0x49, 0xe0, 0xcd, 0xf7, 0x18, 0x47, 0x20, 0xde, 0xa6, 0x70, 0xa3, 0x51, 0x87,
	0xd8, 0x59, 0x53, 0xab, 0xac, 0x11, 0xc2, 0x07, 0x11, 0x88, 0x36, 0xd7, 0x11, 0xd7, 0x2c, 0x61,
	0x9a, 0xfd, 0x6f, 0xa0, 0xf3, 0x12, 0xdf, 0xcd, 0x2c, 0xc3, 0xdd, 0x0b, 0xd0, 0xc9, 0xbd, 0xf3,
	0xa7, 0xc4, 0xfe, 0x63, 0xc6, 0x68, 0x67, 0x4a, 0x56, 0x41, 0xad, 0xaa, 0x7c, 0xab, 0x57, 0x17,
	0x1f, 0x6d, 0x36, 0xb5, 0xea, 0xf7, 0x7c, 0x8a, 0xf0, 0xad, 0x08, 0x84, 0xf3, 0x09, 0xef, 0xdb,
	0xa7, 0x70, 0xc9, 0xc6, 0x66, 0x90, 0x6a, 0x9e, 0x5e, 0xb0, 0xcb, 0xa9, 0x6e, 0x1f, 0x0c, 0x7f,
	0xfd, 0x19, 0xed, 0x79, 0x8e, 0x4b, 0xff, 0xdd, 0x3a, 0xca, 0x4b, 0xfa, 0x67, 0x7c, 0x67, 0xf5,
	0x10, 0x8d, 0x6d, 0x9c, 0xb5, 0xbc, 0xe3, 0x9d, 0x56, 0x15, 0x75, 0x6c, 0xa2, 0x1e, 0x3b, 0x8d,
	0xed, 0xa8, 0xc4, 0x52, 0x6e, 0x7f, 0x5d, 0x8c, 0x4f, 0xd1, 0xc5, 0x9b, 0x1f, 0x33, 0x1f, 0x4d,
	0x66, 0x3e, 0x9a, 0xce, 0x7c, 0xf4, 0x6d, 0xee, 0xd7, 0x26, 0x73, 0xbf, 0xf6, 0x7b, 0xee, 0xd7,
	0x3e, 0x3c, 0x13, 0xa9, 0xbe, 0xea, 0xc6, 0xe4, 0x52, 0x65, 0x86, 0xd2, 0x1f, 0x7c, 0x31, 0xdf,
	0x33, 0x48, 0xae, 0x69, 0xdf, 0x32, 0xf5, 0x20, 0xe7, 0x10, 0xef, 0x9b, 0xa5, 0x7d, 0xfe, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x4d, 0x3d, 0xbf, 0x63, 0x4f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Enable enables the access control based on the allowed list.
	Enable(ctx context.Context, in *MsgEnable, opts ...grpc.CallOption) (*MsgEnableResponse, error)
	// Disable disables the access control based on the allowed list.
	Disable(ctx context.Context, in *MsgDisable, opts ...grpc.CallOption) (*MsgDisableResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Enable(ctx context.Context, in *MsgEnable, opts ...grpc.CallOption) (*MsgEnableResponse, error) {
	out := new(MsgEnableResponse)
	err := c.cc.Invoke(ctx, "/saga.admin.v1.Msg/Enable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Disable(ctx context.Context, in *MsgDisable, opts ...grpc.CallOption) (*MsgDisableResponse, error) {
	out := new(MsgDisableResponse)
	err := c.cc.Invoke(ctx, "/saga.admin.v1.Msg/Disable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Enable enables the access control based on the allowed list.
	Enable(context.Context, *MsgEnable) (*MsgEnableResponse, error)
	// Disable disables the access control based on the allowed list.
	Disable(context.Context, *MsgDisable) (*MsgDisableResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Enable(ctx context.Context, req *MsgEnable) (*MsgEnableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable not implemented")
}
func (*UnimplementedMsgServer) Disable(ctx context.Context, req *MsgDisable) (*MsgDisableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.admin.v1.Msg/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Enable(ctx, req.(*MsgEnable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.admin.v1.Msg/Disable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Disable(ctx, req.(*MsgDisable))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "saga.admin.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enable",
			Handler:    _Msg_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _Msg_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saga/admin/v1/tx.proto",
}

func (m *MsgEnable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDisable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDisableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetMetadataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetMetadataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetMetadataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgEnable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgEnableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDisable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDisableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetMetadataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgEnable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &types.Metadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetMetadataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetMetadataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetMetadataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
