// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: saga/assetctl/host/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgManageSupportedAssets struct {
	Authority       string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	AddIbcDenoms    []string `protobuf:"bytes,2,rep,name=add_ibc_denoms,json=addIbcDenoms,proto3" json:"add_ibc_denoms,omitempty"`
	RemoveIbcDenoms []string `protobuf:"bytes,3,rep,name=remove_ibc_denoms,json=removeIbcDenoms,proto3" json:"remove_ibc_denoms,omitempty"`
}

func (m *MsgManageSupportedAssets) Reset()         { *m = MsgManageSupportedAssets{} }
func (m *MsgManageSupportedAssets) String() string { return proto.CompactTextString(m) }
func (*MsgManageSupportedAssets) ProtoMessage()    {}
func (*MsgManageSupportedAssets) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{0}
}
func (m *MsgManageSupportedAssets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgManageSupportedAssets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgManageSupportedAssets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgManageSupportedAssets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgManageSupportedAssets.Merge(m, src)
}
func (m *MsgManageSupportedAssets) XXX_Size() int {
	return m.Size()
}
func (m *MsgManageSupportedAssets) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgManageSupportedAssets.DiscardUnknown(m)
}

var xxx_messageInfo_MsgManageSupportedAssets proto.InternalMessageInfo

func (m *MsgManageSupportedAssets) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgManageSupportedAssets) GetAddIbcDenoms() []string {
	if m != nil {
		return m.AddIbcDenoms
	}
	return nil
}

func (m *MsgManageSupportedAssets) GetRemoveIbcDenoms() []string {
	if m != nil {
		return m.RemoveIbcDenoms
	}
	return nil
}

type MsgManageSupportedAssetsResponse struct {
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgManageSupportedAssetsResponse) Reset()         { *m = MsgManageSupportedAssetsResponse{} }
func (m *MsgManageSupportedAssetsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgManageSupportedAssetsResponse) ProtoMessage()    {}
func (*MsgManageSupportedAssetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{1}
}
func (m *MsgManageSupportedAssetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgManageSupportedAssetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgManageSupportedAssetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgManageSupportedAssetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgManageSupportedAssetsResponse.Merge(m, src)
}
func (m *MsgManageSupportedAssetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgManageSupportedAssetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgManageSupportedAssetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgManageSupportedAssetsResponse proto.InternalMessageInfo

func (m *MsgManageSupportedAssetsResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type MsgRegisterDenoms struct {
	Authority string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	IbcDenoms []string `protobuf:"bytes,2,rep,name=ibc_denoms,json=ibcDenoms,proto3" json:"ibc_denoms,omitempty"`
}

func (m *MsgRegisterDenoms) Reset()         { *m = MsgRegisterDenoms{} }
func (m *MsgRegisterDenoms) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDenoms) ProtoMessage()    {}
func (*MsgRegisterDenoms) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{2}
}
func (m *MsgRegisterDenoms) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDenoms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDenoms.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDenoms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDenoms.Merge(m, src)
}
func (m *MsgRegisterDenoms) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDenoms) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDenoms.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDenoms proto.InternalMessageInfo

func (m *MsgRegisterDenoms) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRegisterDenoms) GetIbcDenoms() []string {
	if m != nil {
		return m.IbcDenoms
	}
	return nil
}

type MsgRegisterDenomsResponse struct {
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgRegisterDenomsResponse) Reset()         { *m = MsgRegisterDenomsResponse{} }
func (m *MsgRegisterDenomsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDenomsResponse) ProtoMessage()    {}
func (*MsgRegisterDenomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{3}
}
func (m *MsgRegisterDenomsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDenomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDenomsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDenomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDenomsResponse.Merge(m, src)
}
func (m *MsgRegisterDenomsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDenomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDenomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDenomsResponse proto.InternalMessageInfo

func (m *MsgRegisterDenomsResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type MsgCreateICAOnHub struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgCreateICAOnHub) Reset()         { *m = MsgCreateICAOnHub{} }
func (m *MsgCreateICAOnHub) String() string { return proto.CompactTextString(m) }
func (*MsgCreateICAOnHub) ProtoMessage()    {}
func (*MsgCreateICAOnHub) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{4}
}
func (m *MsgCreateICAOnHub) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateICAOnHub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateICAOnHub.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateICAOnHub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateICAOnHub.Merge(m, src)
}
func (m *MsgCreateICAOnHub) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateICAOnHub) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateICAOnHub.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateICAOnHub proto.InternalMessageInfo

func (m *MsgCreateICAOnHub) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgCreateICAOnHubResponse struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PortId    string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
}

func (m *MsgCreateICAOnHubResponse) Reset()         { *m = MsgCreateICAOnHubResponse{} }
func (m *MsgCreateICAOnHubResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateICAOnHubResponse) ProtoMessage()    {}
func (*MsgCreateICAOnHubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{5}
}
func (m *MsgCreateICAOnHubResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateICAOnHubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateICAOnHubResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateICAOnHubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateICAOnHubResponse.Merge(m, src)
}
func (m *MsgCreateICAOnHubResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateICAOnHubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateICAOnHubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateICAOnHubResponse proto.InternalMessageInfo

func (m *MsgCreateICAOnHubResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgCreateICAOnHubResponse) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

type MsgUpdateParams struct {
	Authority string  `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{6}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37bd8a6c69b6a6e1, []int{7}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgManageSupportedAssets)(nil), "saga.assetctl.host.v1.MsgManageSupportedAssets")
	proto.RegisterType((*MsgManageSupportedAssetsResponse)(nil), "saga.assetctl.host.v1.MsgManageSupportedAssetsResponse")
	proto.RegisterType((*MsgRegisterDenoms)(nil), "saga.assetctl.host.v1.MsgRegisterDenoms")
	proto.RegisterType((*MsgRegisterDenomsResponse)(nil), "saga.assetctl.host.v1.MsgRegisterDenomsResponse")
	proto.RegisterType((*MsgCreateICAOnHub)(nil), "saga.assetctl.host.v1.MsgCreateICAOnHub")
	proto.RegisterType((*MsgCreateICAOnHubResponse)(nil), "saga.assetctl.host.v1.MsgCreateICAOnHubResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "saga.assetctl.host.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "saga.assetctl.host.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("saga/assetctl/host/v1/tx.proto", fileDescriptor_37bd8a6c69b6a6e1) }

var fileDescriptor_37bd8a6c69b6a6e1 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x1c, 0x5d, 0x56, 0x18, 0xd4, 0x4c, 0x9d, 0x16, 0x6d, 0x6a, 0x1b, 0xa9, 0x51, 0x55, 0x21, 0x54,
	0x55, 0x5a, 0x4c, 0x87, 0x60, 0x12, 0x07, 0xa4, 0x6e, 0x1c, 0xa8, 0x50, 0x05, 0x4a, 0xc5, 0x05,
	0x0e, 0x95, 0x13, 0x7b, 0x6e, 0x44, 0x13, 0x87, 0xd8, 0xa9, 0xda, 0x9d, 0x80, 0x4f, 0xb0, 0x8f,
	0xb2, 0xc3, 0x3e, 0x04, 0xc7, 0x09, 0x71, 0xe0, 0x88, 0xda, 0xc3, 0xbe, 0x06, 0x8a, 0x93, 0x76,
	0xfd, 0x97, 0xa9, 0x8c, 0x53, 0xfb, 0xf3, 0x7b, 0x7e, 0xef, 0xfd, 0x9c, 0x9f, 0x0d, 0x74, 0x8e,
	0x28, 0x82, 0x88, 0x73, 0x22, 0x6c, 0xd1, 0x83, 0x5d, 0xc6, 0x05, 0xec, 0xd7, 0xa1, 0x18, 0x18,
	0x7e, 0xc0, 0x04, 0x53, 0xf7, 0x23, 0xdc, 0x98, 0xe0, 0x46, 0x84, 0x1b, 0xfd, 0xba, 0xb6, 0x47,
	0x19, 0x65, 0x92, 0x01, 0xa3, 0x7f, 0x31, 0x59, 0xcb, 0xdb, 0x8c, 0xbb, 0x8c, 0x43, 0x97, 0xd3,
	0x48, 0xc4, 0xe5, 0x34, 0x01, 0x8a, 0x31, 0xd0, 0x89, 0x77, 0xc4, 0x45, 0x02, 0x95, 0x57, 0x07,
	0x90, 0x46, 0xc9, 0x66, 0xca, 0x18, 0xed, 0x11, 0x28, 0x2b, 0x2b, 0x3c, 0x85, 0xc8, 0x1b, 0xc6,
	0x50, 0xe5, 0x52, 0x01, 0x85, 0x16, 0xa7, 0x2d, 0xe4, 0x21, 0x4a, 0xda, 0xa1, 0xef, 0xb3, 0x40,
	0x10, 0xdc, 0x88, 0xc4, 0xb8, 0xfa, 0x02, 0x64, 0x51, 0x28, 0xba, 0x2c, 0x70, 0xc4, 0xb0, 0xa0,
	0x94, 0x95, 0x6a, 0xf6, 0xb8, 0xf0, 0xf3, 0xf2, 0x60, 0x2f, 0xb1, 0x6f, 0x60, 0x1c, 0x10, 0xce,
	0xdb, 0x22, 0x70, 0x3c, 0x6a, 0xde, 0x50, 0xd5, 0xc7, 0x20, 0x87, 0x30, 0xee, 0x38, 0x96, 0xdd,
	0xc1, 0xc4, 0x63, 0x2e, 0x2f, 0x6c, 0x96, 0x33, 0xd5, 0xac, 0xb9, 0x8d, 0x30, 0x6e, 0x5a, 0xf6,
	0x6b, 0xb9, 0xa6, 0xd6, 0xc0, 0x6e, 0x40, 0x5c, 0xd6, 0x27, 0xb3, 0xc4, 0x8c, 0x24, 0xee, 0xc4,
	0xc0, 0x94, 0xfb, 0x32, 0xf7, 0xfd, 0xfa, 0xa2, 0x76, 0xe3, 0x50, 0x79, 0x05, 0xca, 0x69, 0xa9,
	0x4d, 0xc2, 0x7d, 0xe6, 0x71, 0xa2, 0x6a, 0xe0, 0x21, 0x27, 0x5f, 0x42, 0xe2, 0xd9, 0x44, 0x86,
	0xbf, 0x67, 0x4e, 0xeb, 0xca, 0x19, 0xd8, 0x6d, 0x71, 0x6a, 0x12, 0xea, 0x70, 0x41, 0x82, 0x24,
	0xd0, 0x5d, 0xdb, 0x2d, 0x01, 0xb0, 0xd4, 0x6a, 0xd6, 0x49, 0xcd, 0x7e, 0x04, 0x8a, 0x4b, 0xde,
	0x6b, 0x85, 0xfe, 0x24, 0x43, 0x9f, 0x04, 0x04, 0x09, 0xd2, 0x3c, 0x69, 0xbc, 0xf3, 0xde, 0x84,
	0xd6, 0x5d, 0x43, 0x2f, 0xa5, 0x6a, 0xcb, 0x54, 0xf3, 0xe2, 0xd3, 0x54, 0x25, 0x00, 0xec, 0x2e,
	0xf2, 0x3c, 0xd2, 0xeb, 0x38, 0x38, 0x76, 0x31, 0xb3, 0xc9, 0x4a, 0x13, 0xab, 0x79, 0xf0, 0x20,
	0xfa, 0x02, 0x11, 0xb6, 0x29, 0xb1, 0xad, 0xa8, 0x6c, 0xe2, 0xca, 0xb9, 0x02, 0x76, 0x5a, 0x9c,
	0x7e, 0xf0, 0x31, 0x12, 0xe4, 0x3d, 0x0a, 0xd0, 0x7f, 0x9c, 0xf2, 0x73, 0xb0, 0xe5, 0x4b, 0x05,
	0xe9, 0xf1, 0xe8, 0xb0, 0x64, 0xac, 0xbc, 0x58, 0x46, 0x6c, 0x63, 0x26, 0xe4, 0xa5, 0x3e, 0x8b,
	0x20, 0xbf, 0x90, 0x68, 0xd2, 0xe5, 0xe1, 0xaf, 0x0c, 0xc8, 0xb4, 0x38, 0x55, 0xbf, 0x29, 0x60,
	0x7f, 0xf5, 0x85, 0x80, 0x29, 0x9e, 0x69, 0xb3, 0xa8, 0x1d, 0xfd, 0xe3, 0x86, 0xe9, 0x89, 0xf7,
	0x40, 0x6e, 0x61, 0x3a, 0xab, 0xe9, 0x52, 0xf3, 0x4c, 0xed, 0xe9, 0xba, 0xcc, 0x59, 0xb7, 0x85,
	0xb1, 0xba, 0xc5, 0x6d, 0x9e, 0x79, 0x9b, 0x5b, 0xca, 0x34, 0x9d, 0x82, 0xed, 0xb9, 0x89, 0x78,
	0x92, 0xae, 0x30, 0xcb, 0xd3, 0x8c, 0xf5, 0x78, 0x13, 0x1f, 0xed, 0xfe, 0xd7, 0xeb, 0x8b, 0x9a,
	0x72, 0xfc, 0xf6, 0xc7, 0x48, 0x57, 0xae, 0x46, 0xba, 0xf2, 0x67, 0xa4, 0x2b, 0xe7, 0x63, 0x7d,
	0xe3, 0x6a, 0xac, 0x6f, 0xfc, 0x1e, 0xeb, 0x1b, 0x1f, 0xeb, 0xd4, 0x11, 0xdd, 0xd0, 0x32, 0x6c,
	0xe6, 0xc2, 0x48, 0x7a, 0x30, 0x3c, 0x93, 0xbf, 0x07, 0x1c, 0x7f, 0x86, 0x83, 0x85, 0x27, 0x55,
	0x0c, 0x7d, 0xc2, 0xad, 0x2d, 0xf9, 0x6c, 0x3e, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x23, 0x54,
	0x0a, 0x9d, 0xf6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SupportAssets sends a message to the controller to let it know that this host
	// supports the given assets.
	ManageSupportedAssets(ctx context.Context, in *MsgManageSupportedAssets, opts ...grpc.CallOption) (*MsgManageSupportedAssetsResponse, error)
	// RegisterDenom sends a message to the controller to let it know that this host
	// registers the given denom as a native asset of the host.
	RegisterDenoms(ctx context.Context, in *MsgRegisterDenoms, opts ...grpc.CallOption) (*MsgRegisterDenomsResponse, error)
	CreateICAOnHub(ctx context.Context, in *MsgCreateICAOnHub, opts ...grpc.CallOption) (*MsgCreateICAOnHubResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ManageSupportedAssets(ctx context.Context, in *MsgManageSupportedAssets, opts ...grpc.CallOption) (*MsgManageSupportedAssetsResponse, error) {
	out := new(MsgManageSupportedAssetsResponse)
	err := c.cc.Invoke(ctx, "/saga.assetctl.host.v1.Msg/ManageSupportedAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterDenoms(ctx context.Context, in *MsgRegisterDenoms, opts ...grpc.CallOption) (*MsgRegisterDenomsResponse, error) {
	out := new(MsgRegisterDenomsResponse)
	err := c.cc.Invoke(ctx, "/saga.assetctl.host.v1.Msg/RegisterDenoms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateICAOnHub(ctx context.Context, in *MsgCreateICAOnHub, opts ...grpc.CallOption) (*MsgCreateICAOnHubResponse, error) {
	out := new(MsgCreateICAOnHubResponse)
	err := c.cc.Invoke(ctx, "/saga.assetctl.host.v1.Msg/CreateICAOnHub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/saga.assetctl.host.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SupportAssets sends a message to the controller to let it know that this host
	// supports the given assets.
	ManageSupportedAssets(context.Context, *MsgManageSupportedAssets) (*MsgManageSupportedAssetsResponse, error)
	// RegisterDenom sends a message to the controller to let it know that this host
	// registers the given denom as a native asset of the host.
	RegisterDenoms(context.Context, *MsgRegisterDenoms) (*MsgRegisterDenomsResponse, error)
	CreateICAOnHub(context.Context, *MsgCreateICAOnHub) (*MsgCreateICAOnHubResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ManageSupportedAssets(ctx context.Context, req *MsgManageSupportedAssets) (*MsgManageSupportedAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageSupportedAssets not implemented")
}
func (*UnimplementedMsgServer) RegisterDenoms(ctx context.Context, req *MsgRegisterDenoms) (*MsgRegisterDenomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDenoms not implemented")
}
func (*UnimplementedMsgServer) CreateICAOnHub(ctx context.Context, req *MsgCreateICAOnHub) (*MsgCreateICAOnHubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateICAOnHub not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ManageSupportedAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgManageSupportedAssets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ManageSupportedAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.assetctl.host.v1.Msg/ManageSupportedAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ManageSupportedAssets(ctx, req.(*MsgManageSupportedAssets))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterDenoms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterDenoms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterDenoms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.assetctl.host.v1.Msg/RegisterDenoms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterDenoms(ctx, req.(*MsgRegisterDenoms))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateICAOnHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateICAOnHub)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateICAOnHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.assetctl.host.v1.Msg/CreateICAOnHub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateICAOnHub(ctx, req.(*MsgCreateICAOnHub))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.assetctl.host.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "saga.assetctl.host.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ManageSupportedAssets",
			Handler:    _Msg_ManageSupportedAssets_Handler,
		},
		{
			MethodName: "RegisterDenoms",
			Handler:    _Msg_RegisterDenoms_Handler,
		},
		{
			MethodName: "CreateICAOnHub",
			Handler:    _Msg_CreateICAOnHub_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saga/assetctl/host/v1/tx.proto",
}

func (m *MsgManageSupportedAssets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgManageSupportedAssets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgManageSupportedAssets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemoveIbcDenoms) > 0 {
		for iNdEx := len(m.RemoveIbcDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RemoveIbcDenoms[iNdEx])
			copy(dAtA[i:], m.RemoveIbcDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RemoveIbcDenoms[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AddIbcDenoms) > 0 {
		for iNdEx := len(m.AddIbcDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddIbcDenoms[iNdEx])
			copy(dAtA[i:], m.AddIbcDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddIbcDenoms[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgManageSupportedAssetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgManageSupportedAssetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgManageSupportedAssetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterDenoms) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDenoms) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDenoms) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IbcDenoms) > 0 {
		for iNdEx := len(m.IbcDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.IbcDenoms[iNdEx])
			copy(dAtA[i:], m.IbcDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.IbcDenoms[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterDenomsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDenomsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDenomsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateICAOnHub) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateICAOnHub) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateICAOnHub) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateICAOnHubResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateICAOnHubResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateICAOnHubResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgManageSupportedAssets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.AddIbcDenoms) > 0 {
		for _, s := range m.AddIbcDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RemoveIbcDenoms) > 0 {
		for _, s := range m.RemoveIbcDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgManageSupportedAssetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	return n
}

func (m *MsgRegisterDenoms) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.IbcDenoms) > 0 {
		for _, s := range m.IbcDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRegisterDenomsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	return n
}

func (m *MsgCreateICAOnHub) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateICAOnHubResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgManageSupportedAssets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgManageSupportedAssets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgManageSupportedAssets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddIbcDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddIbcDenoms = append(m.AddIbcDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveIbcDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoveIbcDenoms = append(m.RemoveIbcDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgManageSupportedAssetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgManageSupportedAssetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgManageSupportedAssetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterDenoms) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDenoms: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDenoms: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenoms = append(m.IbcDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterDenomsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDenomsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDenomsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateICAOnHub) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateICAOnHub: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateICAOnHub: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateICAOnHubResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateICAOnHubResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateICAOnHubResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
